### ISSUE TITLE
Fix camera bugs that makes us reset the roborio before streaming

### ISSUE THREAD

**Issue by RyanMarten** [1757WestwoodRobotics/2017-Steamworks#20]
Probably has to do something with existing networktable objects reserving cameras already

**Comment by 1757Robotics** [comment]
Now we have ability to stream both cameras at the same time, however we want to toggle. Also the second camera is using 8 FPS and the first one is using 30 fps. So configuration of the cameras is needed.

**Comment by 1757Robotics** [comment]
Completely fixed cameras. Both stream at the same time:  2c1ea1e3de445da265a7178ed2a820a1d912478d
